# Introduction to Numpy arrays

In [1]:
import numpy as np

### One dimensional arrays
* select the first item using `arr.item(0)` or `arr[0]`
* `.item()` returns a copy of the element.
* Using `[]` accesses the element directly.
* Try looking at the types of both!

In [2]:
#:
a = np.array([1,2,3,4,5,6])

In [3]:
elt_copy = a.item(0)
print(elt_copy)
print(type(elt_copy))

1
<class 'int'>


In [4]:
elt_direct = a[0]
print(elt_direct)
print(type(elt_direct))

1
<class 'numpy.int64'>


### Change the third element of an array to `2022` via:
* `a[2] = 2022`

In [5]:
a[2] = 2022
a

array([   1,    2, 2022,    4,    5,    6])

### Comparisons return boolean arrays
* Each element of the boolean array is True/False if the comparison is True/False for the corresponding element in the original array.

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,4,2])

In [7]:
print(a)
print(a > 2)

[1 2 3 4 5]
[False False  True  True  True]


In [8]:
print(sum(a > 2))

3


In [9]:
print(a)
print(b)
print(a < b)

[1 2 3 4 5]
[2 3 4 4 2]
[ True  True  True False False]


### Change the elements of an array that correspond to `True` in a boolean array.
* Set every element of `a` that is greater than 2 equal to `2018`.
* Set every even element of `b` to zero.

In [10]:
a[a > 2] = 2019

In [11]:
a > 2

array([False, False,  True,  True,  True])

In [12]:
a

array([   1,    2, 2019, 2019, 2019])

In [13]:
# using modulus: %

print(b)
print(b % 2 == 0)

[2 3 4 4 2]
[ True False  True  True  True]


In [14]:
b[b % 2 == 0] = 0

In [15]:
b

array([0, 3, 0, 0, 0])

### Multi-dimensional arrays
* define them using nested lists
* see the shape using `.shape`
* change shape/dimension using `.reshape(shape)`

### Creating 2-dimensional arrays (matrices)
* Example, black-and-white images are 2-dimensional arrays of pixels, where each element is an intensity between 0 and 256 (black is 0, white is 256).

In [16]:
a2 = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

In [17]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:
a2.shape

(4, 3)

In [19]:
a2.reshape(3,4)

array([[1, 2, 3, 2],
       [3, 4, 3, 4],
       [5, 4, 5, 6]])

In [20]:
a2.reshape(a2.size)

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

### Selecting rows and columns
* `a[i,j]` selects the element in the ith row and jth column (0-indexed!)
* `a[:,j]` selects the jth column.
* `a[i,:]` selects the ith column.

In [21]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
a2[0,2]

3

In [23]:
a2[:,2]

array([3, 4, 5, 6])

In [24]:
a2[2,:]

array([3, 4, 5])

### Change elements using boolean arrays

In [25]:
a2[a2 % 2 == 0] = 0

In [26]:
a2

array([[1, 0, 3],
       [0, 3, 0],
       [3, 0, 5],
       [0, 5, 0]])

### 3 dimensional arrays
* Example, color pictures are 3 dimensional arrays: a triplet of 2D arrays (one for red intensities, one for green intensities, one for blue intensities).

In [27]:
a3 = np.array([
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]]
])

In [28]:
a3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [29]:
a3.shape

(3, 3, 2)

In [30]:
a3.reshape(a3.size)

array([1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4])

In [31]:
a3[0,:,:]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [32]:
a3[:,0,:]

array([[1, 2],
       [1, 2],
       [1, 2]])

In [33]:
a3[:,:,0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
# EXCERCISE:
# 1. create a 100x100 matrix of numbers with uniformly distributed 
# elements 
# 2. calculate the mean of each column
# 3. calculate the total mean
#
# 3. how do we create a 100x100 matrix of numbers with a normal 
# distribution and mean=100 ? (let's search online "numpy normal distribution")
# 4. calculate the mean to check if our approximation is good!



In [35]:
matrix = np.random.uniform(0,1,(10,10))

In [36]:
matrix

array([[0.11303616, 0.23469742, 0.90446531, 0.14493586, 0.27738871,
        0.981738  , 0.13981461, 0.41408767, 0.20476221, 0.89999935],
       [0.67529538, 0.28484695, 0.9206372 , 0.03032005, 0.1412866 ,
        0.00153911, 0.47381147, 0.54445977, 0.38671882, 0.91770713],
       [0.50163164, 0.55171545, 0.27979924, 0.27428367, 0.53880705,
        0.55553644, 0.3159508 , 0.563091  , 0.87218912, 0.12042512],
       [0.40891796, 0.08445465, 0.40153269, 0.63880896, 0.75380134,
        0.96182109, 0.20112083, 0.85902844, 0.774898  , 0.44069793],
       [0.53722226, 0.46612774, 0.17680122, 0.71612675, 0.30786371,
        0.64984532, 0.21538558, 0.48614733, 0.02558234, 0.53004618],
       [0.79940839, 0.38069896, 0.26679758, 0.39983205, 0.98199223,
        0.44401417, 0.85976476, 0.54676844, 0.89371212, 0.11388179],
       [0.6644347 , 0.59435793, 0.47093176, 0.15525728, 0.98632394,
        0.4291694 , 0.94395574, 0.40318827, 0.8504687 , 0.0803553 ],
       [0.52156054, 0.92870561, 0.9531338